name: Git Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  automate-git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full commit history
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Prevent Workflow Loop
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$LAST_COMMIT_MSG" == *"[skip ci]"* ]]; then
            echo "Last commit contains [skip ci]. Exiting..."
            exit 0
          fi

      - name: Make Changes (Optional)
        run: |
          echo "Automated update at $(date)" >> changes.log

      - name: Commit & Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions [skip ci]" || exit 0
          
          # Create a temporary branch
          git branch temp-auto
          git checkout temp-auto
          git push https://x-access-token:${GH_PAT}@github.com/meghaabhi/mygitactions.git temp-auto

          # Merge back to main without triggering CI
          git checkout main
          git merge temp-auto --no-ff -m "Merging automation changes [skip ci]"
          git push https://x-access-token:${GH_PAT}@github.com/meghaabhi/mygitactions.git main
          
          # Delete the temp branch
          git push https://x-access-token:${GH_PAT}@github.com/meghaabhi/mygitactions.git --delete temp-auto



