name: Git Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  automate-git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Prevent Workflow Loop
        run: |
          LAST_COMMITTER=$(git log -1 --pretty=format:'%an')
          if [[ "$LAST_COMMITTER" == "GitHub Actions" ]]; then
            echo "Last commit was from GitHub Actions. Exiting..."
            exit 0
          fi

      - name: Make Changes (Optional)
        run: |
          echo "Automated update at $(date)" >> changes.log

      - name: Commit & Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions" || exit 0
          git push https://x-access-token:${GH_PAT}@github.com/meghaabhi/mygitactions.git HEAD:main



