name: Git Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  automate-git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable default GitHub authentication

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Make Changes (Optional)
        run: |
          echo "Automated update at $(date)" >> changes.log

      - name: Commit & Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Using Personal Access Token (PAT)
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/meghaabhi/mygitactions.git HEAD:main


